---
permalink: cors
title: CORS
category: security
---

= CORS

toc::[]

Cross-Origin Resource Sharing(CORS) is a way to allow incoming HTTP requests from different domains. It is very common in AJAX applications where the browser blocks all cross-domain requests if the server does not authorize them. Read more about CORS link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[here, window="_blank"].

== Setup
Install the middleware provider from npm by executing the following command.

[source, bash]
----
adonis install @adonisjs/cors
----

Next, register the provider inside `start/app.js` file.

.start/app.js
[source, javascript]
----
const providers = [
  '@adonisjs/cors/providers/CorsProvider'
]
----

The middleware will be registered inside `start/kernel.js` file.

[source, js]
----
Server
  .use(['Adonis/Middleware/Cors'])
----

== Config
The configuration for CORS is defined inside `config/cors.js` file and accepts following options.

==== origin
The origin(s) to be allowed for making cross-domain requests. You can return one of the following values.

[ul-spaced]
- A boolean `true` or `false` to deny the current request origin.
- A comma-separated strings of domains to be allowed.
- An array of domains to be allowed.
- A function, which receives current request origin. Here you can compute whether or not the origin is allowed by returning true or false.
+
[source, js]
----
origin: function (currentOrigin) {
  return currentOrigin === 'mywebsite.com'
}
----

For all other options, go through the comments inside the link:https://github.com/adonisjs/adonis-cors/blob/develop/config/cors.js#L3[config file, window="_blank"].
