---
title: Encryption and Hashing
permalink: encryption-and-hashing
category: security
---

= Encryption and Hashing

toc::[]

AdonisJs comes with a couple of providers for *hashing values* and *encrypting data*. Hashing values are different from encryption since hashed values cannot be decrypted once encrypted that is not the case with encryption.

== Encrypting Data

AdonisJs encryption provider makes use of link:https://nodejs.org/api/crypto.html[Node.js crypto module, window="_blank"] to encrypt and decrypt values.

NOTE: Make sure that *appKey* inside `config/app.js` is defined before you can encrypt values.

==== encrypt(value)
[source, javascript]
----
const Encryption = use('Encryption')
const encrypted = Encryption.encrypt('hello world')
----

==== decrypt
[source, javascript]
----
const Encryption = use('Encryption')
const decrypted = Encryption.decrypt('encrypted value')
----

== Hashing Values
AdonisJs hash provider comes with multiple drivers to hash user data. By default it makes use of link:https://en.wikipedia.org/wiki/Bcrypt[bcrypt, window="_blank"], however support Argon via link:https://npm.im/argon2[argon2 npm package, window="_blank"].

NOTE: `@adonisjs/framework` version `>=5.0.8` supports multiple drivers. So make sure to upgrade the package for desired results.

=== Config
The config is defined inside `config/hash.js` file and allows following values.

NOTE: You will have to install link:https://npm.im/argon2[argon2 npm package, window="_blank"] package from npm if using `argon` driver.

[source, js]
----
module.exports = {
  driver: 'bcrypt',
  bcrypt: {
    rounds: 10
  },
  argon: {
    type: 1
  }
}
----

==== make(value, [config])
Hash a plain string value. Optionally inline config can be passed to override the defaults inside the config file.

[source, javascript]
----
const Hash = use('Hash')
const safePassword = await Hash.make(request.input('password'))
----

==== verify(value, hashedValue)
Since you cannot decrypt a hash, you can verify the user input against the previously hashed value.

[source, javascript]
----
const Hash = use('Hash')
const isSame = await Hash.verify('plain-value', 'hashed-value')

if (isSame) {
  // ...
}
----

