---
title: About AdonisJs
permalink: about
category: introduction
---
= About AdonisJs

toc::[]

AdonisJs is a Node.js MVC framework that runs on all the main operating systems. It offers you a stable eco-system to write web servers so that you can focus on business needs over finalizing which package to choose or not.

AdonisJs favors developer joy with consistent and expressive API to build full-stack web-servers or a micro API server.

== Getting started
The are no hard pre requisites to use AdonisJs, but having a conventional understanding of Javascript, Async programming, and Node.js is great.

Also, make sure to go through the link:installation[getting started] guide especially if this is your first time using AdonisJs.

== Other sources
Here are some other great places to find information about AdonisJs.

1. The link:https://forum.adonisjs.com[discourse forum, window="_blank"], where we talk about everything about AdonisJs from fixing bugs to discussing new features.
2. Twitter
3. Github
4. If you love the project, then please consider supporting us on link:https://www.patreon.com/adonisframework[patreon, window="_blank"].

== Providers
AdonisJs is a modular framework that consists of multiple service providers. The service providers are the building blocks of AdonisJs applications.

In theory, they are like any other npm module with some code on top of it to play transparently with AdonisJs applications. For example, link:https://github.com/adonisjs/adonis-bodyparser[BodyParser] to parse HTTP request body or link:https://github.com/adonisjs/adonis-lucid[Lucid] which is a SQL ORM.

== FQA's
Below is the list of frequently asked questions, if you think a common question is missing in the list. Please create an issue link:[here]

[ol-spaced]
1. *How AdonisJs is different from Express or Koa?*
+
Express and Koa are routing libraries with a thin layer of middleware on top of it. There are great for several use cases but falls apart when your project starts growing.
+
Also, it becomes harder to hire someone, since your project has its own standards and conventions. Whereas AdonisJs follows a set of standardized conventions, making it easier to hire people and make them work on existing AdonisJs apps.

2. *Is AdonisJs for monolithic apps?*
+
No. AdonisJs as a framework is a combination of multiple packages that gracefully integrates with the rest of your app.
+
The framework provides a robust *Dependency injection* layer, which is leveraged by all official and 3rd party packages to offer functionality without manually wiring up each part of the application.
