---
title: Upgrading from 3.x
permalink: upgrade-guide
category: introduction
---

toc::[]

AdonisJs 4.0, known as *(dawn)* is a major release of the framework after more than a year. Each major release comes with handful of breaking changes, which is required to keep the framework fresh and address all issues reported during the year.

== Javascript movement
This release is even special, since lot of movement has happened in ES6 and Node.js 8.0 has implemented 99% of the link:http://node.green/[language features].

Also link:https://v8project.blogspot.in/2017/08/v8-release-61.html[V8 engine] has been updated with lots of speed improvements.

Finally, the time was to update the code base and start supporting latest features, so that we all can write simpler and expressive code, while gaining all performance benefits.

== Language changes
Below is the list of changes made due to availability of ES6 features.

==== Using async/await
Generator functions using `yield` keyword is no more supported and instead we make use of `async/await` now.

Which means all functions starting with `*` needs to be replaced with `async` and `yield` keyword will be replaced with `await`.

Old way
[source, js]
----
* index () {
  yield User.all()
}
----

New way
[source, js]
----
async index () {
  await User.all()
}
----

==== Destructuring
ES6 allows link:https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring[Object destructuring] which can be used to pull selected values from an object. This feature is really powerful and intuitive to build API's around passing parameters.

In newer of AdonisJs, all route handlers and controller actions will receive an object of values, instead of receiving multiple parameters with `request` and `response`.

Old Way
[source, js]
----
Route.get('/', function * (request, response) {

})
----

New Way
[source, js]
----
Route.get('/', async ({ request, response }) => {

})
----
