---
title: Controllers
category: basics
permalink: controllers
---

= Controllers

toc::[]

It may be enough to write closure to handle your route for a small application, but when your application starts growing it could be useful to organise them. This is where Controllers enter in the dance floor.

Controllers are attached to one or many routes and are the common point of interaction between your models, views and any other services you may need.

[NOTE]
Controllers only job is to respond to an HTTP request. Do not use them internally by requiring them inside different files.
[/NOTE]

== Creating Controllers

To create a new controller, make use of the `make:controller` command.

[source, bash]
----
> adonis make:controller User --type http # HTTP Controller
> adonis make:controller User --type ws   # WS Controller
> adonis make:controller Admin/User       # Will use an Admin subfolder
----

This command will create a file in the `App/Controllers/{TYPE}` folder with some boilerplate code.

TIP: You can use the `--resource` flag to create a resourceful controller.

.app/Controllers/Http/UserController.js
[source, js]
----
'use strict'

class UserController {
}

module.exports = UserController
----

== Using a Controller

A controller can be only accessed from a route. This is done by referencing them as a **String** in your route definition.

[source, js]
----
Route.get(url, 'UserController.index')
----

The part before the dot (`.`) is a reference to the controller file. It is by default namespaced to `App/Controller/Http`. The second part is the name of the method you want to call inside this controller.

[source, js]
----
// App/Controller/Http/UserController -> index()
Route.get(url, 'UserController.index')

// App/Controller/Http/Admin/UserController -> store()
Route.post(url, 'Admin/UserController.store')

// App/MyOwnController/UserController -> index()
Route.post(url, 'App/MyOwnController/UserController.index')
----

Since these methods are route handlers, they will receive as an argument the link:http-context#_http_context[HTTP Context].

[source, js]
----
'use strict'

class UserController {
  index ({ request, response }) {
    //
  }
}

module.exports = UserController
----
