---
title: Logger
permalink: logger
category: basics
---

= Logger

toc::[]

AdonisJs comes with a fully featured logger built on top of link:https://github.com/winstonjs/winston[winston]. It follows link:https://tools.ietf.org/html/rfc5424#page-11[RFC5424] logging levels.

Logger ships with following *drivers*. However, you free to add your drivers built on top of Winston transports.

[ol-shrinked]
1. Console ( console )
2. File ( file )

== Configuration
The configuration for logger is saved inside `config/app.js` file under `logger` object.

[source, js]
----
logger: {
  transport: 'console',
  console: {
    driver: 'console'
  },
  file: {
    driver: 'file',
    filename: 'adonis.log'
  }
}
----

The `file` driver saves the file inside `tmp` directory. However, you can define an absolute path to a different location.

== Basic example
Let's start with a basic example of logging data within your app. Also, all logging methods support link:http://www.diveintojavascript.com/projects/javascript-sprintf[sprintf] syntax.

[source, js]
----
const Logger = use('Logger')

Logger.info('request url is %s', request.url())

Logger.info('request details %j', {
  url: request.url(),
  user: auth.user.username()
})
----

The logger follows link:https://tools.ietf.org/html/rfc5424#page-11[RFC5424] levels to log messages. Also, it exposes readable methods for each level.

[options="header", cols="20%,20%,60%"]
|====
| Level | Method | Usage
| 0 | emerg | `Logger.emerg(msg, ...data)`
| 1 | alert | `Logger.alert(msg, ...data)`
| 2 | crit | `Logger.crit(msg, ...data)`
| 3 | error | `Logger.error(msg, ...data)`
| 4 | warning | `Logger.warning(msg, ...data)`
| 5 | notice | `Logger.notice(msg, ...data)`
| 6 | info | `Logger.info(msg, ...data)`
| 7 | debug | `Logger.debug(msg, ...data)`
|====

== Switching transports
You can switch transports on the fly using the `transport` method.

[source, js]
----
Logger
  .transport('file')
  .info('request url is %s', request.url())
----

== Logging level
Logger always has a certain logging level set via config file, which can be updated at runtime too. Any messages above the defined logging level are not logged. For example:

[source, js]
----
const Logger = use('Logger')
Logger.level = 'info'

// not logged
Logger.debug('Some debugging info')

Logger.level = 'debug'

// now logged
Logger.debug('Some debugging info')
----

This approach makes it easier to turn off debugging messages when your server is under high load.

