---
title: Logger
permalink: logger
category: basics
---

= Logger

toc::[]

AdonisJs comes with a fully featured logger built on top of link:https://github.com/winstonjs/winston[winston, window="_blank"], using link:https://tools.ietf.org/html/rfc5424#page-11[RFC5424] logging levels.

Logger ships with the following drivers:

[ol-shrinked]
1. Console (`console`)
2. File (`file`)

You are free to add your own drivers built on top of link:https://github.com/winstonjs/winston#transports[winston transports].

== Configuration
The configuration for Logger is saved inside the `config/app.js` file under the `logger` object:

.config/app.js
[source, js]
----
logger: {
  transport: 'console',
  console: {
    driver: 'console'
  },
  file: {
    driver: 'file',
    filename: 'adonis.log'
  }
}
----

The `file` driver saves your log file inside the application root `tmp` directory.

NOTE: You can define an absolute `filename` path to a different log file location if you wish.

== Basic example
Let's start with a basic example of logging data within your app:

[source, js]
----
const Logger = use('Logger')

Logger.info('request url is %s', request.url())

Logger.info('request details %j', {
  url: request.url(),
  user: auth.user.username()
})
----

TIP: All logging methods support link:http://www.diveintojavascript.com/projects/javascript-sprintf[sprintf] syntax.

The logger uses link:https://tools.ietf.org/html/rfc5424#page-11[RFC5424] log levels, exposing simple methods for each level:

[options="header", cols="20%,20%,60%"]
|====
| Level | Method | Usage
| 0 | emerg | `Logger.emerg(msg, ...data)`
| 1 | alert | `Logger.alert(msg, ...data)`
| 2 | crit | `Logger.crit(msg, ...data)`
| 3 | error | `Logger.error(msg, ...data)`
| 4 | warning | `Logger.warning(msg, ...data)`
| 5 | notice | `Logger.notice(msg, ...data)`
| 6 | info | `Logger.info(msg, ...data)`
| 7 | debug | `Logger.debug(msg, ...data)`
|====

== Switching transports
You can switch transports on the fly using the `transport` method:

[source, js]
----
Logger
  .transport('file')
  .info('request url is %s', request.url())
----

== Logging level
Logger has a default config logging `level` which can be updated at runtime.

Any messages above the defined logging level are not logged. For example:

[source, js]
----
const Logger = use('Logger')
Logger.level = 'info'

// not logged
Logger.debug('Some debugging info')

Logger.level = 'debug'

// now logged
Logger.debug('Some debugging info')
----

This approach could make it easier to turn off debugging messages when your server is under high load.

