---
permalink: release-notes
categories:
- prologue
---
= Release Notes

toc::[]

== How Release Is Managed?
AdonisJs is a combination of multiple npm packages called *Service providers*. All packages are free to have their own release cycle and versions. The combination of these packages form a release for AdonisJs. In brief you should look into the version number in `package.json` file of your project to know the current version.

== AdonisJs 3.2
Release v3.2 is a minor update with handful or bug fixes and incremental API updates. All features/methods from *v3.1* are fully supported and compatible with *v3.2*. Below is the changelog for individual modules.

==== adonis-framework (3.0.4 - 3.0.9)
There are no notable changes for this repo and all existing features from 3.1 will continue to work. Checkout the link:https://github.com/adonisjs/adonis-framework/blob/develop/CHANGELOG.md[git changelog, window="_blank"]

==== adonis-lucid (3.0.8 - 3.0.13)
Below is the list of notable changes:

1. Add support for updating and `belongsToMany` pivot table and fetch additional columns using `withPivot` method. link:https://github.com/adonisjs/adonis-lucid/commit/1d00425[Related commit]
2. Model static interface now has `first` and `last` methods to pull first and last rows from a table related to a model. link:https://github.com/adonisjs/adonis-lucid/commit/2a74d6e[Related commit]
+
[source, javascript]
----
yield User.first()
yield User.last()
----

Checkout the entire link:https://github.com/adonisjs/adonis-lucid/blob/develop/CHANGELOG.md[git chanagelog, window="_blank"].

==== adonis-auth(1.0.5)
Below is the list of notable changes:

1. You can now pass custom object to the JWT token when generating it. It can be helpful to add some meta information to the token to be read on the client side. link:https://github.com/adonisjs/adonis-auth/commit/2e413fe[Related commit].
+
[source, javascript]
----
// Save custom payload
yield request.auth.generate(user, {
  isAdmin: true
})

// Get custom payload
const payload = yield request.auth.getPayload()
----

Checkout the entire link:https://github.com/adonisjs/adonis-auth/blob/develop/CHANGELOG.md[git changelog, window="_blank"]

==== adonis-commands(2.1.5)
There are no notable changes for this repo and all existing features from 3.1 will continue to work. Checkout the
Checkout the entire link:https://github.com/adonisjs/adonis-commands/blob/develop/CHANGELOG.md[git chanagelog].
