---
title: AdonisJs at a Glance
permalink: adonisjs-at-a-glance
---

== AdonisJs at a Glance

:toc:

AdonisJs is a https://nodejs.org[Node.js] Framework with pre-configured answers to all of your questions. It encapsulates the boring parts of Web development and offers you a nice and clean API to work with.

Every web application needs the same functionalities at a certain stage. AdonisJs has all of this built right into the framework or can be added by using one of the official library.

1. Powerful https://en.wikipedia.org/wiki/Object-relational_mapping[ORM] to make secure SQL queries.
2. API & Session based Authentication System.
3. Easy way to send emails via SMTP or Web Service (Mailgun, Sparkpost, Mandrill, ...)
4. Validate & Sanitise every user's inputs.
5. Simple application layout.

=== Conventions Over Configuration

This software paradigm is the core of AdonisJs. We attempt to *decrease the time you loose* when taking decisions by following well-kown convention through popular Framework like Rails, Django or Laravel without losing any flexibility. For example, if there you have a User model the corresponding table in the database should be named `users` by default (of course you can change this by overiding a property on your model).

You can learn more about this paradigm on https://en.wikipedia.org/wiki/Convention_over_configuration[the wikipedia page].

=== Simplest Example

As we said, AdonisJs attempts to remove the big pieces of unmanageable code with *simple readable API*.

1. AdonisJs removes the unnecessary callbacks from your code and introduces https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators[ES2015 Generators].
2. It organises everything into different directories so that you can easily know where are your files. 
3. It does not add anything to the globals except the `use` and `make` function that you will learn about them soon.

If we tell you that within 6 lines of code you are able to fetch all users from database and send them back as `JSON` response could you believe us?

[source, javascript]
----
const Route = use('Route')
const User = use ('App/Model/User')

Route.get('/', function * (request, response) {
    const users = yield User.all()
    response.json(users)
})
----

Hopefully this quick overview has intrigant you and don't worry if you do not fully understand the code above the Getting Started chapter is for you!