---
title: Client API
permalink: websocket-client
category: websockets
---
= Client API

toc::[]

This guide covers the JavaScript *WebSocket client* used to connect to the link:websocket-server[WebSocket server].

== Installation

=== NPM
As the *WebSocket client* is not installed by default, we need to pull it from `npm`:

[source, bash]
----
> npm i @adonisjs/websocket-client
----

TIP: Once installed, bundle the package using Webpack, Rollup, etc.

Then, import the WebSocket client like so:

[source, js]
----
import Ws from '@adonisjs/websocket-client'
const ws = Ws('ws://localhost:3333')
----

=== UNPKG

Alternatively, source the UMD bundle directly from link:https://unpkg.com[unpkg, window="_blank"]:
[source, html]
----
<script src="https://unpkg.com/@adonisjs/websocket-client"></script>
<script>
  const ws = adonis.Ws('ws://localhost:3333')
</script>
----

== Polyfill
The module build requires the link:https://babeljs.io/docs/plugins/transform-regenerator[regenerator-runtime, window="_blank"] polyfill (add it via link:https://babeljs.io[Babel, window="_blank"]).

== Production Builds
As the development build contains a number of log statements, we recommend defining `NODE_ENV` via link:https://webpack.js.org/plugins/define-plugin/[Webpack DefinePlugin, window="_blank"] or link:https://github.com/rollup/rollup-plugin-replace[rollup-plugin-replace, window="_blank"].

== Getting Started
Connect to a WebSocket server via the client like so:

[source, js]
----
const ws = Ws(url, options)

// connect to the server
ws.connect()
----

NOTE: The `url` parameter will fallback to the current hostname if a full `ws://` url value is omitted.

==== options

[role="resource-table", options="header", cols="30%, 10%, 60%"]
|===
| Key | Default Value | Description
| `path` | `adonis-ws` | The path used to make the connection (only change if you changed it on the server).
| `reconnection` | `true` | Whether to reconnect automatically after disconnect.
| `reconnectionAttempts` | `10` | Number of reconnection attempts before abandoning.
| `reconnectionDelay` | `1000` | How long to wait before reconnecting. The value will be used as `n x delay`, where `n` is the current value of reconnection attempts.
| `query` | `null` | Query string to pass to the connection URL (also accepts an object).
| `encoder` | `JsonEncoder` | The encoder to use (the same encoder will be required on the server).
|===

To manage your application state, listen for the `open`/`close` events:

[source, js]
----
let isConnected = false

ws.on('open', () => {
  isConnected = true
})

ws.on('close', () => {
  isConnected = false
})
----

Once connected, subscribe to different/multiple topics:

[source, js]
----
const chat = ws.subscribe('chat')

chat.on('ready', () => {
  chat.emit('message', 'hello')
})

chat.on('error', (error) => {
  console.log(error)
})

chat.on('close', () => {
})
----

== Subscription API
The following methods are used to send/receive messages.

==== emit(event, data)
Send event to the server:

[source, js]
----
chat.emit('message', {
  body: 'hello',
  user: 'virk'
})
----

==== on(event, callback)
Bind event listener:

[source, js]
----
chat.on('message', () => {})
chat.on('new:user', () => {})
----

==== off(event, callback)
Remove event listener:

[source, js]
----
const messageHandler = function () {}

chat.on('message', messageHandler)
chat.off('message', messageHandler)
----

==== close()
Initiate request to close the subscription:

[source, js]
----
chat.on('close', () => {
  // server acknowledged close
})

chat.close()
----

NOTE: Listen for the link:#_close_2[close event] to confirm the subscription closed.

==== leaveError
Emitted when the server refuses to close the subscription:

[source, js]
----
chat.on('leaveError', (response) => {
  console.log(response)
})
----

==== error
Emitted when an error occurs on the TCP connection:

[source, js]
----
chat.on('error', (event) => {
})
----

NOTE: Preferably, listen for the `ws.on('error')` event instead.

==== close
Emitted when the subscription is closed:

[source, js]
----
chat.on('close', () => {
})
----

== Ws API
The following methods are available on a single `ws` connection.

==== connect
Initiate the connection:

[source, js]
----
ws.connect()
----

==== close
Forcefully close the connection:

[source, js]
----
ws.close()
----

NOTE: Removes all subscriptions and does not trigger a reconnection.

==== getSubscription(topic)
Returns the subscription instance for a given topic:

[source, js]
----
ws.subscribe('chat')

ws.getSubscription('chat').on('message', () => {
})
----

NOTE: If no subscriptions for the given topic, returns `null`.

==== subscribe(topic)
Subscribe to a topic:

[source, js]
----
const chat = ws.subscribe('chat')
----

NOTE: Subscribing to the same topic twice raises an exception.

== Authentication
The AdonisJs WebSocket client makes it simple to authenticate users.

Auth credentials are only passed once to the server during the initial connection, so the same information can be reused to allow/disallow channel subscriptions.

NOTE: If your application uses sessions, users will be authenticated automatically providing they have a valid session.

==== withBasicAuth(username, password)
Authenticate via basic auth:

[source, js]
----
const ws = Ws(url, options)

ws
  .withBasicAuth(username, password)
  .connect()
----

==== withApiToken(token)
Authenticate via api token:

[source, js]
----
const ws = Ws(url, options)

ws
  .withApiToken(token)
  .connect()
----

==== withJwtToken(token)
Authenticate via JWT token:

[source, js]
----
const ws = Ws(url, options)

ws
  .withJwtToken(token)
  .connect()
----

=== User Information

On the server, access user information via the `auth` object:

.start/socket.js
[source, js]
----
Ws.channel('chat', ({ auth }) => {
  console.log(auth.user)
})
----

NOTE: link:websocket-server#_registering_middleware[Required middleware] must be set up to access the `auth` object.

=== Channel Middleware

To authenticate connections, ensure the `auth` named middleware is applied:

.start/socket.js
[source, js]
----
Ws.channel('chat', ({ auth }) => {
  console.log(auth.user)
}).middleware(['auth'])
----
