---
permalink: database-setup
categories:
- database
---
= Database Setup

toc::[]

AdonisJs has out of the box for SQL databases and offers a unified Javascript API to interact with databases. Below is the list of supported databases.

== Supported Databases
[support-list]
* PostgreSQL
* SQLite
* MySQL
* MariaDB
* Oracle
* MSSQL

== Configuration
Every AdonisJs application ships with the pre-configured support for link:query-build[Query builder] and link:lucid[Lucid Orm] all you have to do is tweak the configuration as per your needs.

By default Adonis is set to use *SqLite* as the default db driver, which you are free to change it either through the `config/database.js` file.

.config/database.js
[source, javascript]
----
module.exports = {
  connection: Env.get('DB_CONNECTION', 'sqlite'), <1>

  sqlite: {
    ....
  }, <2>

  mysql: {
    ....
  }
}
----

<1> `connection` property defines the default connection to be used for making SQL queries.
<2> Individual connection config is set next to the connection name.

or through the *.env* file

.(.env)
[source]
----
DB_CONNECTION=sqlite
----

== Database Drivers & Their Settings
Since AdonisJs supports all popular SQL databases, you have to install their equivalent drivers from npm and configure them as defined below.

TIP: note that you need to have the Db (sqlite, mysql, etc...) installed on your system first before installing the driver.

=== SQLite
Available Driver(s)::
link:https://www.npmjs.com/package/sqlite3[sqlite3]

=== MySQL
Available Driver(s)::
link:https://www.npmjs.com/package/mysql[mysql] +
link:https://www.npmjs.com/package/mysql2[mysql2]

Configuration::
+

TIP: if you want, you can instead define a socket path to building the MySQL connection. Giving the socket path will ignore the host and port options.

[source, javascript]
----
mysql: {
  client: 'mysql',
  connection: {
    socketPath: '/path/to/socket.sock',
    user: 'root',
    password: '',
    database: 'adonis'
  }
}
----

=== MariaDB
Available Driver(s)::
link:https://www.npmjs.com/package/mariasql[mariasql]

=== MSSQL
Available Driver(s)::
link:https://www.npmjs.com/package/mssql[mssql]

=== PostgreSQL
Available Driver(s)::
link:https://www.npmjs.com/package/pg[pg]

Configuration::
+

TIP: if you want, you can instead pass a connection string

[source, javascript]
----
pg: {
  client: 'pg',
  connection: 'postgres://user:password@host:port/database?ssl=true'
}
----

=== Oracle
Available Driver(s)::
link:https://www.npmjs.com/package/oracle[oracle] +
link:https://www.npmjs.com/package/strong-oracle[strong-oracle]


== Debugging
Debugging database queries are handy to check database response time or to make sure that the query builder performs the correct query. Let's go through a handful of different debugging strategies.

=== Globally
The easiest way to globally debug queries is to set the `debug` flag on the configuration block.

.config/database.js
[source, javascript]
----
mysql: {
  client: 'mysql',
  connection: {},
  debug: true <1>
}
----

Also, you can turn debugging on within your code by listening for the `query` or `sql` events on the Database provider. The best place to register a listener is under `app/Listeners/Http.js` file.

.app/Listeners/Http.js
[source, javascript]
----
Http.onStart = function () {
  Database.on('query', console.log)
  Database.on('sql', console.log)
}
----

The only difference between `query` and the `sql` event is the output.

SQL event output::
+

[source, mysql]
----
+ 1.38 ms : select * from `users` where `username` = 'doe'
----

Query event output::
+

[source, javascript]
----
{
  method: 'select',
  options: {},
  bindings: [ 'doe' ],
  sql: 'select * from `users` where `username` = ?'
}
----

=== Individual Query
Also, you can debug a single query by chaining the event listener when running the query.

[source, javascript]
----
yield Database
  .on('sql', console.log)
  .table('users')
  .where('username', 'doe')
----

Or

[source, javascript]
----
yield Database
  .debug()
  .table('users')
  .where('username', 'doe')
----
