---
title: Contribution Guide
category: Preface
permalink: contribution-guide
---

= Contribution Guide

toc::[]

Open Source projects are maintained and backed by a **vibrant community** of users and collaborators.

We encourage you to participate actively in the development and the future of AdonisJs either by contributing to the source code, improving documentation, reporting potential bugs and/or testing new features.

== Channels

There are many ways to communicate with the AdonisJs team.

1. link:https://github.com/adonisjs[Github Repositories, window="_blank"]: Share bugs or create feature requests against the dedicated AdonisJs repositories.
2. link:https://forum.adonisjs.com[Forum, window="_blank"]: Ask questions, showcase your project and participate in the life of the AdonisJs Framework.
3. link:https://discord.gg/vDcEjq6[Discord, window="_blank"]: Join our Discord Server to chat instantly with others in the community.
4. link:https://twitter.com/adonisframework[Twitter, window="_blank"]: Stay in touch with the progress we make each day and be informed about awesome projects provided by the community.

== Bug Reports

Providing a great bug report can seem simple at first glance.

Always try to be descriptive and provide enough context and information to reproduce the issue.

Bug reports may also be sent in the form of a pull request containing a failing test.

1. Provide a clear title and description of the issue.
2. Share the version of the framework you are on.
3. Add as much code samples as you can to demonstrate the issue. You can also provide a complete repository to reproduce the issue quickly.

Remember, bug reports don't mean the bug will be fixed within an hour!

It serves yourself and the broader community to start on the path of fixing the problem before reporting it.

== Coding Style

Unfortunately, JavaScript doesn’t have any official coding style.

For this reason, AdonisJs uses link:https://standardjs.com/[StandardJS, window="_blank"] to help maintain a readable and consistent codebase.

Please ensure you lint your code before sending pull requests to any AdonisJs repositories:

[source, shell]
----
> npm run lint
----

== Documentation

When adding a new feature to the core of the framework, be sure to create a parallel pull request in the link:https://github.com/adonisjs/docs[documentation repository] and link them.

This will help the AdonisJs team understand your feature and keep the documentation updated.

== Testing

Before providing a pull request be sure to test the feature you are adding or create a regression test to show how a piece of code fails under specific circumstance while providing a bug fix.
