---
permalink: request
title: Request
category: http-lifecycle
---

toc::[]

This guide gives an outline on how to make use of the HTTP link:https://github.com/adonisjs/adonis-framework/blob/develop/src/Request/index.js[Request] object to read data for a request.

AdonisJs passes the current HTTP request object as part of the `context` which is sent to all route handlers and middleware.

[source, js]
----
Route.get('/', ({ request }) => {
})
----

TIP: The Node.js raw `req` object can be accessed as `request.request`.

We used link:https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment[ES6 destructuring] to get the `request` object from context.

== Request body
The request object offers a bunch of helpful methods to read the request body. First make sure that you have installed the bodyparser middleware.

If not, follow the upcoming steps.

=== Setting up bodyparser
NOTE: Fullstack and API only boilerplates comes with pre-configured bodyparser.

[source, js]
----
adonis install @adonisjs/bodyparser
----

Then register the provider inside `start/app.js` file
[source, js]
----
const providers = [
  '@adonisjs/bodyparser/providers/BodyParserProvider'
]
----

Also register the global middleware inside `start/kernel.js` file.
[source, js]
----
const globalMiddleware = [
  'Adonis/Middleware/BodyParser'
]
----

==== all
Returns the entire request body as an object. This method will merge the `query params` with the `request body`.

[source, js]
----
const all = request.all()
----

==== get
Get an object of query params

[source, js]
----
const query = request.get()
----

==== post
Get an object of just request body

[source, js]
----
const body = request.post()
----

==== raw
Get data posted as raw body.

NOTE: If raw data is JSON with `Content-type: application/json`, then the bodyparser will parse it smartly and returns it as part of `post` method.

[source, js]
----
const body = request.raw()
----

==== only
Returns an object with `only` specified keys

[source, js]
----
const body = request.only('username', 'email', 'age')
----

==== except
The opposite of `only` and returns everything except defined keys.

[source, js]
----
const body = request.except('csrf_token', 'submit')
----

==== input
Get value for a given key only, and it doesn't exists, return the `default` value.

[source, js]
----
const drink = request.input('drink')

// with default value
const drink = request.input('drink', 'coffee')
----


== Request collection
Quite often you want to handle HTML forms that submits an array of data over key/value pairs. For example: A form to create multiple users at once.

When you get the data back, it is not in consumable format and requires some extra processing.

[source, html]
----
<form method="POST" action="/users">
  <input type="text" name="username[0]" />
  <input type="text" name="age[0]" />

  <hr>
  <input type="text" name="username[1]" />
  <input type="text" name="age[1]" />
</form>
----

Let's say we want to get the username and age inside the controller.

[source, js]
----
const users = request.only('username', 'age')

// output
{ username: ['virk', 'nikk'], age: [26, 25] }
----

The above piece of data is something that you cannot save to the database directly, since it is not in the right format.

Using `request.collect` we can get it formatted out of the box.

[source, js]
----
const users = request.collect('username', 'age')

// output
[{ username: 'virk', age: 26 }, { username: 'nikk', age: 25 }]

// save to db
await User.createMany(users)
----

== Headers
Also you can read headers from the request using one of the following methods.

==== header
The value for a given key. Also this method will handle case inconsistencies.

[source, js]
----
const auth = request.header('authorization')

// different word case
const auth = request.header('Authorization')
----

==== headers
Returns an object of headers.

[source, js]
----
const headers = request.headers()
----

== Cookies
Cookies are read using one of the following methods

==== cookie
Returns the value for a key inside cookies. Optionally returns the default value.

[source, js]
----
const cartTotal = request.cookie('cart_total')

// with default value
const cartTotal = request.cookie('cart_total', 0)
----

==== cookies
Returns an object of all the cookies

[source, js]
----
const cookies = request.cookies()
----

Since all cookies are *encrypted* and *signed* automatically. Use one of the following methods, in case you want to access a plain cookie set by some frontend code.

==== plainCookie
[source, js]
----
const jsCookie = request.plainCookie('cart_total')
----

==== plainCookies
Get an object of raw cookies
[source, js]
----
const plainCookies = request.plainCookies()
----

== Content negotiation
link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[Content negotiation] is a way for server and client to decide upon the best response type to be returned from the server.

NOTE: Content negotiation can also be done on the basis on route formats. Learn more about it link:routing#_route_formats[here]

Since web servers do not only serve web pages, they have to deal with API response in *JSON*, or maybe in *XML*. Instead of creating seperate URL's for each content type, the consumer can ask the server to return the response in specific format.

Now in order to construct the response in specific format, the server needs to be know it first. The same can be done using the `accepts` method.

==== accepts
[source, js]
----
const bestFormat = request.accepts(['json', 'html'])

if (bestFormat === 'json') {
  return response.json(users)
}

return view.render('users.list', { users })
----

==== language
Language can also be negotiated based upon `Accept-Language` header.

[source, js]
----
const language = request.language(['en', 'fr'])
----

== Request methods
Following is the list of all request methods and their usage example

==== url
Returns the current request url

[source, js]
----
const url = request.url()
----

==== originalUrl
The url with query strings on it

[source, js]
----
const url = request.originalUrl()
----

==== method
Returns the request HTTP method.

[source, js]
----
const method = request.method()
----

==== intended
Since Adonisjs allows xref:_method_spoofing[method spoofing], you can fetch the actual method using `intended` method.

[source, js]
----
const method = request.intended()
----

==== ip
Returns the most trusted ip address of the user.

[source, js]
----
const ip = request.ip()
----

==== ips
Returns an array of ips from most to the least trusted one. It will remove the default ip address, which can be accessed via `ip` method.

[source, js]
----
const ips = request.ips()
----

==== subdomains
Returns a list of request subdomains, this method will remove `www` from the list.

[source, js]
----
const subdomains = request.subdomains()
----

==== ajax
Is request an ajax request based upon `X-Requested-With` header.

[source, js]
----
if (request.ajax()) {
  // do something
}
----

==== pjax
link:https://github.com/defunkt/jquery-pjax[Pjax] is an evolved way to make use of Ajax to deliver better user experience on traditional apps. In rails world, it is know as Turbolinks.

This methods looks at `X-PJAX` header to identify if request is pjax or not.
[source, js]
----
if (request.pjax()) {
  // do something
}
----

==== hostname
Returns the request hostname

[source, js]
----
const hostname = request.hostname()
----

==== protocol
Return request protocol.

[source, js]
----
const protocol = request.protocol()
----

==== match
Matches a set of expressions against the current request url to tell if it matches one.

[source, js]
----
// current request url - posts/1

request.match(['posts/:id']) // returns true
----

==== hasBody
A boolean indicating if request has post body.  This is mainly used by the bodyparser to know whether to parse the body or not.

[source, js]
----
if (request.hasBody()) {
  // do something
}
----

==== is
The is method returns the best matching content type for current request. The check is entirely based upon the `content-type` header.

[source, js]
----
// assuming content-type is `application/json`

request.is(['json', 'html']) // returns - json

request.is(['application/*']) // returns - application/json
----

== Extending Request
Quite often you have the requirement of extending the `Request` prototype by attaching new methods. Same can be done by defining a macro on the Request class.

==== Application Specific
If your macros are specific to your application only, you can add the macro inside `start/hooks.js` file after the providers have been booted.

.start/hooks.js
[source, javascript]
----
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
  const Request = use('Adonis/Src/Request')

  Request.macro('cartValue', function () {
    return this.cookie('cartValue', 0)
  })
})
----

==== Via Provider
If you are writing a module/addon for AdonisJs, you can add a macro inside the `boot` method of your service provider.

[source, javascript]
----
const { ServiceProvider } = require('@adonisjs/fold')

class MyServiceProvider extends ServiceProvider {
  boot () {
    const Request = use('Adonis/Src/Request')

    Request.macro('cartValue', function () {
      return this.cookie('cartValue', 0)
    })
  }
}
----

Defined macros can be used like any other `request` method.

[source, javascript]
----
const cartValue = request.cartValue()
----
